from .nodes import NODE_CLASS_MAPPINGS as CONTINUITY_NODES, NODE_DISPLAY_NAME_MAPPINGS as CONTINUITY_NAMES
from .retake import NODE_CLASS_MAPPINGS as RETAKE_NODES, NODE_DISPLAY_NAME_MAPPINGS as RETAKE_NAMES

NODE_CLASS_MAPPINGS = {**CONTINUITY_NODES, **RETAKE_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**CONTINUITY_NAMES, **RETAKE_NAMES}
__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
