from .nodes import NODE_CLASS_MAPPINGS as CONTINUITY_NODES, NODE_DISPLAY_NAME_MAPPINGS as CONTINUITY_NAMES
from .retake import NODE_CLASS_MAPPINGS as RETAKE_NODES, NODE_DISPLAY_NAME_MAPPINGS as RETAKE_NAMES
from .bridge import NODE_CLASS_MAPPINGS as BRIDGE_NODES, NODE_DISPLAY_NAME_MAPPINGS as BRIDGE_NAMES
from .checkpoints import NODE_CLASS_MAPPINGS as CHECKPOINT_NODES, NODE_DISPLAY_NAME_MAPPINGS as CHECKPOINT_NAMES
from .joint import NODE_CLASS_MAPPINGS as JOINT_NODES, NODE_DISPLAY_NAME_MAPPINGS as JOINT_NAMES
from .latent_assembly import NODE_CLASS_MAPPINGS as LATENT_NODES, NODE_DISPLAY_NAME_MAPPINGS as LATENT_NAMES

from .frame_counts import NODE_CLASS_MAPPINGS as COUNT_NODES, NODE_DISPLAY_NAME_MAPPINGS as COUNT_NAMES

from .latent_split import NODE_CLASS_MAPPINGS as SPLIT_NODES, NODE_DISPLAY_NAME_MAPPINGS as SPLIT_NAMES

from .audio_cut import NODE_CLASS_MAPPINGS as AUDIO_CUT_NODES, NODE_DISPLAY_NAME_MAPPINGS as AUDIO_CUT_NAMES

NODE_CLASS_MAPPINGS = {**CONTINUITY_NODES, **RETAKE_NODES, **BRIDGE_NODES, **CHECKPOINT_NODES, **JOINT_NODES, **LATENT_NODES, **COUNT_NODES, **SPLIT_NODES, **AUDIO_CUT_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**CONTINUITY_NAMES, **RETAKE_NAMES, **BRIDGE_NAMES, **CHECKPOINT_NAMES, **JOINT_NAMES, **LATENT_NAMES, **COUNT_NAMES, **SPLIT_NAMES, **AUDIO_CUT_NAMES}
__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
