import json,sys,pathlib,requests
REPO=pathlib.Path(__file__).resolve().parents[2];sys.path.insert(0,str(REPO/'scripts'));from gpu_workflows import build_continuation_chain
BASE=REPO/'milestones/gpu_validation/executed/source.api.json';HERE=pathlib.Path(__file__).resolve().parent
scenarios={
'jungle':(23601, 'One continuous photorealistic cinematic adventure shot, full body view of an adult female explorer with tied black hair, mustard yellow field jacket, dark cargo trousers, brown hiking boots and a small brown backpack. She runs briskly toward the right along a narrow trail through a dense tropical jungle, naturally stepping over roots and jumping over low fallen logs without stopping. The camera tracks smoothly sideways beside her at running speed, maintaining enough distance to show her whole body and feet. Dense green foliage and tree trunks pass in the background, foreground leaves occasionally partially obscure her. Humid afternoon sunlight and dappled shadows, realistic anatomy and fast athletic motion, consistent outfit. A single uninterrupted camera take. Audio: rapid footsteps on damp soil, rustling foliage, birds and breathing, no music, no dialogue.'),
'combat':(34702, 'One continuous photorealistic cinematic adventure action shot, medium wide full body view of two adult swordsmen sparring in a sunlit ancient stone courtyard. The first fighter has short dark hair and wears a navy blue tunic with brown leather armor and dark trousers; the second has short light hair and wears a burgundy tunic with dark leather armor. Each holds one steel sword. They continuously exchange controlled sword strikes, blocks, sidesteps and small lunges while circling, keeping both fighters fully visible. Their swords meet naturally and remain in their hands. The camera moves in a smooth slow arc around the pair, following the sparring without cutting. Fine dust rises at their feet, stable warm late afternoon light, realistic anatomy, cloth motion and stone texture. A single uninterrupted camera take, no teleportation. Audio: sword clashes, boot steps on stone and exertion, no music, no dialogue.'),
'snow':(45803, 'One continuous photorealistic cinematic adventure chase shot, wide full body view of an adult woman with dark hair, a tan leather coat and a vivid red scarf riding one black horse at a sustained fast gallop toward the right through a snowy mountain forest. The rider leans forward and holds the reins naturally; the red scarf streams backward and the horses legs cycle with physically plausible galloping motion. Snow sprays from the hooves. The camera tracks smoothly alongside the horse at matching speed, with a gentle handheld action-camera feel, keeping the complete horse and rider visible. Snowy pine trees and distant mountains pass behind them, occasional foreground tree trunks create brief partial occlusions. Cold clear daylight, stable neutral colors, detailed leather and fur. A single uninterrupted camera take. Audio: galloping hooves on packed snow, wind, horse breathing, no music, no dialogue.')}
submitted=[]
def submit(name,g):
 p=HERE/'api'/(name+'.api.json');p.write_text(json.dumps(g,indent=2)+'\n');x=requests.post('http://127.0.0.1:8188/prompt',json={'prompt':g}).json();print(name,x,flush=True);(HERE/'api'/(name+'.submit.json')).write_text(json.dumps(x,indent=2));submitted.append({'name':name,**x})
for scene,(seed,prompt) in scenarios.items():
 g=json.loads(BASE.read_text());g['5']['inputs']['prompt']=prompt;g['8']['inputs']['noise_seed']=seed
 for node,key in [('15','filename_prefix'),('16','filename'),('17','filename_prefix')]:g[node]['inputs'][key]=f'h3_action_validation/{scene}/source'+('.safetensors' if node=='16' else '')
 submit(scene+'_source',g)
 for mode in (['hard','feather'] if scene=='combat' else ['hard']):
  g=build_continuation_chain(source_latent=f'h3_action_validation/{scene}/source.safetensors',clips=3,seed=seed+1000,mode=mode,reference=True,feather_frames=17,feather_strength=1.,label=scene+'_'+mode,prompt=prompt)
  g=json.loads(json.dumps(g).replace('h3_validation/{{RUN_ID}}/',f'h3_action_validation/{scene}/'))
  submit(scene+'_'+mode,g)
(HERE/'submissions.json').write_text(json.dumps(submitted,indent=2)+'\n');(HERE/'scenarios.json').write_text(json.dumps({k:{'seed':s,'prompt':p} for k,(s,p) in scenarios.items()},indent=2)+'\n')
